In [67]:
import pandas as pd
import numpy as np

In [8]:
data = pd.read_excel("여가활동통계.xlsx", header=None)

In [16]:
data.iloc[57] = data.iloc[57].replace(method='ffill')

In [25]:
data1 = data.iloc[57:67, :12].drop(1,axis=1).reset_index(drop=True)
data1

        0      2      3      4      5      6      7      8      9     10    11
0      NaN  65-69  65-69  70-74  70-74  75-79  75-79  80-84  80-84  85이상  85이상
1      NaN      남      여      남      여      남      여      남      여     남     여
2   문화예술관람   0.14   0.16   0.09   0.11   0.05   0.07   0.02   0.02  0.01  0.03
3   문화예술참여   0.71    0.8   0.64   0.76   0.57   0.69   0.23   0.35  0.07  0.18
4    스포츠관람   0.06   0.07   0.04   0.04   0.02   0.02   0.01   0.01  0.01  0.02
5    스포츠참여   1.71   1.92   1.12   1.32   0.94   1.15   0.35   0.56  0.15  0.38
6       관광    0.1   0.11   0.06   0.08   0.06   0.07   0.05   0.07  0.03  0.07
7     취미오락    4.7   5.31   3.42   4.02   2.85   3.48   1.46   2.28  0.57  1.41
8     휴식활동   3.76   4.24   3.06   3.59   2.33   2.84   1.34   2.09  0.65   1.6
9  사회 및 기타   4.36   4.91   3.23   3.79   2.74   3.34    1.6   2.49  0.65  1.59

In [31]:
data1.columns = data1.iloc[0].str.cat(data1.iloc[1], sep=' ')

In [32]:
data1

,nan,65-69 남,65-69 여,70-74 남,70-74 여,75-79 남,75-79 여,80-84 남,80-84 여,85이상 남,85이상 여
0,NaN,65-69,65-69,70-74,70-74,75-79,75-79,80-84,80-84,85이상,85이상
1,NaN,남,여,남,여,남,여,남,여,남,여
2,문화예술관람,0.14,0.16,0.09,0.11,0.05,0.07,0.02,0.02,0.01,0.03
3,문화예술참여,0.71,0.8,0.64,0.76,0.57,0.69,0.23,0.35,0.07,0.18
4,스포츠관람,0.06,0.07,0.04,0.04,0.02,0.02,0.01,0.01,0.01,0.02
5,스포츠참여,1.71,1.92,1.12,1.32,0.94,1.15,0.35,0.56,0.15,0.38
6,관광,0.1,0.11,0.06,0.08,0.06,0.07,0.05,0.07,0.03,0.07
7,취미오락,4.7,5.31,3.42,4.02,2.85,3.48,1.46,2.28,0.57,1.41
8,휴식활동,3.76,4.24,3.06,3.59,2.33,2.84,1.34,2.09,0.65,1.6
9,사회 및 기타,4.36,4.91,3.23,3.79,2.74,3.34,1.6,2.49,0.65,1.59

In [49]:
data1 = data1.drop([0,1], axis=0).reset_index(drop=True)

In [50]:
col = data1.columns.tolist()
col[0] = "분류"
data1.columns = col

In [55]:
data1.set_index("분류", inplace=True)

In [63]:
data1

,65-69 남,65-69 여,70-74 남,70-74 여,75-79 남,75-79 여,80-84 남,80-84 여,85이상 남,85이상 여
분류,,,,,,,,,,
문화예술관람,0.14,0.16,0.09,0.11,0.05,0.07,0.02,0.02,0.01,0.03
문화예술참여,0.71,0.8,0.64,0.76,0.57,0.69,0.23,0.35,0.07,0.18
스포츠관람,0.06,0.07,0.04,0.04,0.02,0.02,0.01,0.01,0.01,0.02
스포츠참여,1.71,1.92,1.12,1.32,0.94,1.15,0.35,0.56,0.15,0.38
관광,0.1,0.11,0.06,0.08,0.06,0.07,0.05,0.07,0.03,0.07
취미오락,4.7,5.31,3.42,4.02,2.85,3.48,1.46,2.28,0.57,1.41
휴식활동,3.76,4.24,3.06,3.59,2.33,2.84,1.34,2.09,0.65,1.6
사회 및 기타,4.36,4.91,3.23,3.79,2.74,3.34,1.6,2.49,0.65,1.59

In [77]:
data2=data1.T
data2

분류      문화예술관람 문화예술참여 스포츠관람 스포츠참여    관광  취미오락  휴식활동 사회 및 기타
65-69 남   0.14   0.71  0.06  1.71   0.1   4.7  3.76    4.36
65-69 여   0.16    0.8  0.07  1.92  0.11  5.31  4.24    4.91
70-74 남   0.09   0.64  0.04  1.12  0.06  3.42  3.06    3.23
70-74 여   0.11   0.76  0.04  1.32  0.08  4.02  3.59    3.79
75-79 남   0.05   0.57  0.02  0.94  0.06  2.85  2.33    2.74
75-79 여   0.07   0.69  0.02  1.15  0.07  3.48  2.84    3.34
80-84 남   0.02   0.23  0.01  0.35  0.05  1.46  1.34     1.6
80-84 여   0.02   0.35  0.01  0.56  0.07  2.28  2.09    2.49
85이상 남    0.01   0.07  0.01  0.15  0.03  0.57  0.65    0.65
85이상 여    0.03   0.18  0.02  0.38  0.07  1.41   1.6    1.59

In [79]:
data2["합"] = data2.apply(np.sum, axis=1)
data2

분류      문화예술관람 문화예술참여 스포츠관람 스포츠참여    관광  취미오락  휴식활동 사회 및 기타      합
65-69 남   0.14   0.71  0.06  1.71   0.1   4.7  3.76    4.36  15.54
65-69 여   0.16    0.8  0.07  1.92  0.11  5.31  4.24    4.91  17.52
70-74 남   0.09   0.64  0.04  1.12  0.06  3.42  3.06    3.23  11.66
70-74 여   0.11   0.76  0.04  1.32  0.08  4.02  3.59    3.79  13.71
75-79 남   0.05   0.57  0.02  0.94  0.06  2.85  2.33    2.74   9.56
75-79 여   0.07   0.69  0.02  1.15  0.07  3.48  2.84    3.34  11.66
80-84 남   0.02   0.23  0.01  0.35  0.05  1.46  1.34     1.6   5.06
80-84 여   0.02   0.35  0.01  0.56  0.07  2.28  2.09    2.49   7.87
85이상 남    0.01   0.07  0.01  0.15  0.03  0.57  0.65    0.65   2.14
85이상 여    0.03   0.18  0.02  0.38  0.07  1.41   1.6    1.59   5.28

In [99]:
data3 = data2.iloc[:,:8].div(data2.iloc[:,8], axis=0)

In [156]:
data3

분류,문화예술관람,문화예술참여,스포츠관람,스포츠참여,관광,취미오락,휴식활동,사회 및 기타
65-69 남,0.00900901,0.0456885,0.003861,0.110039,0.00643501,0.302445,0.241956,0.280566
65-69 여,0.00913242,0.0456621,0.00399543,0.109589,0.00627854,0.303082,0.242009,0.280251
70-74 남,0.0077187,0.0548885,0.00343053,0.0960549,0.0051458,0.29331,0.262436,0.277015
70-74 여,0.00802334,0.055434,0.00291758,0.0962801,0.00583516,0.293217,0.261853,0.276441
75-79 남,0.00523013,0.0596234,0.00209205,0.0983264,0.00627615,0.298117,0.243724,0.286611
75-79 여,0.00600343,0.0591767,0.00171527,0.0986278,0.00600343,0.298456,0.243568,0.286449
80-84 남,0.00395257,0.0454545,0.00197628,0.06917,0.00988142,0.288538,0.264822,0.316206
80-84 여,0.0025413,0.0444727,0.00127065,0.0711563,0.00889454,0.289708,0.265565,0.316391
85이상 남,0.0046729,0.0327103,0.0046729,0.0700935,0.0140187,0.266355,0.303738,0.303738
85이상 여,0.00568182,0.0340909,0.00378788,0.0719697,0.0132576,0.267045,0.30303,0.301136

In [157]:
people_ratio = [159,179,122,143,93,114,45,71,21,53]
data4 = pd.DataFrame()
for i, ratio in enumerate(people_ratio):
    data4 = data4.append([data3.iloc[i]]*ratio)

In [158]:
data4

분류,문화예술관람,문화예술참여,스포츠관람,스포츠참여,관광,취미오락,휴식활동,사회 및 기타
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
...,...,...,...,...,...,...,...,...
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136

In [153]:
np.set_printoptions(suppress = False)
data5 = pd.DataFrame()
for index in data4.index.unique():
    temp = data4.loc[index,:]
    for column in data4.columns:
        normal_random = np.random.normal(temp.loc[index,column].iloc[0], 0.001, len(temp))
        temp.loc[:,column] = normal_random
    data5 = data5.append(temp)

In [154]:
data5.groupby(level=0).mean()

분류,문화예술관람,문화예술참여,스포츠관람,스포츠참여,관광,취미오락,휴식활동,사회 및 기타
65-69 남,0.008318,0.043344,0.003152,0.110464,0.009651,0.302795,0.241890,0.280407
65-69 여,0.010033,0.045358,0.003570,0.110213,0.006833,0.302472,0.242277,0.280506
70-74 남,0.007468,0.057118,0.003610,0.094968,0.003654,0.293533,0.262240,0.274973
70-74 여,0.005404,0.056339,0.002334,0.094916,0.002496,0.292591,0.261484,0.276506
75-79 남,0.004430,0.057247,0.001613,0.100121,0.007050,0.300178,0.243667,0.287336
75-79 여,0.008233,0.057875,-0.000399,0.096288,0.004649,0.298497,0.242958,0.287156
80-84 남,0.001388,0.044170,0.005337,0.068868,0.009716,0.288023,0.263948,0.317184
80-84 여,0.003804,0.045309,-0.000003,0.069623,0.010214,0.291371,0.265644,0.318137
85이상 남,0.005714,0.032352,0.004813,0.070429,0.012841,0.266729,0.304581,0.302065
85이상 여,0.007144,0.034825,0.005928,0.071998,0.013341,0.267033,0.305071,0.299429

In [190]:
data5[~(data5>0).all(1)]

분류,문화예술관람,문화예술참여,스포츠관람,스포츠참여,관광,취미오락,휴식활동,사회 및 기타
70-74 여,0.004973,0.055194,-0.000031,0.093976,0.002741,0.292752,0.262440,0.275789
70-74 여,0.003165,0.056525,-0.000047,0.094066,0.002823,0.291363,0.261691,0.277417
75-79 남,0.004556,0.058648,-0.000154,0.100268,0.008964,0.301400,0.243135,0.286132
75-79 남,0.003551,0.054975,-0.000285,0.099711,0.008032,0.299829,0.243297,0.287010
75-79 남,0.004321,0.057178,-0.000324,0.099016,0.006665,0.301640,0.243375,0.286138
75-79 남,0.004387,0.055622,-0.000043,0.099535,0.009211,0.298644,0.244583,0.287422
75-79 남,0.005683,0.058248,-0.000079,0.099793,0.005568,0.299871,0.243439,0.287808
75-79 남,0.004008,0.057557,-0.000215,0.101315,0.006706,0.298831,0.242512,0.286763
75-79 남,0.004733,0.056252,-0.001016,0.099885,0.007525,0.299340,0.242570,0.284511
75-79 여,0.007698,0.056683,-0.001249,0.097206,0.005100,0.299154,0.243037,0.287098
75-79 여,0.009798,0.059231,-0.000365,0.096352,0.003230,0.300668,0.244221,0.287782
75-79 여,0.008509,0.059233,-0.002174,0.097521,0.005155,0.297722,0.243644,0.287157
75-79 여,0.008557,0.056766,-0.000349,0.095512,0.004909,0.297122,0.244867,0.286896
75-79 여,0.010144,0.059931,-0.001262,0.095978,0.004311,0.298830,0.242901,0.285154
75-79 여,0.006109,0.056473,-0.000209,0.097617,0.003339,0.298304,0.241572,0.287673
75-79 여,0.008397,0.060003,-0.001551,0.096573,0.003254,0.298191,0.244344,0.286711
75-79 여,0.009283,0.056897,-0.002181,0.094839,0.005332,0.297831,0.241237,0.287410
75-79 여,0.007966,0.058661,-0.000395,0.095057,0.005720,0.299203,0.243555,0.286811
75-79 여,0.008792,0.056793,-0.000546,0.096796,0.006123,0.300983,0.244679,0.287436
75-79 여,0.007475,0.056403,-0.000746,0.096618,0.005516,0.298416,0.244106,0.289322
75-79 여,0.009917,0.057577,-0.000651,0.096953,0.003349,0.299797,0.243847,0.287039
75-79 여,0.009257,0.058160,-0.001500,0.096222,0.006337,0.298255,0.243789,0.287937
75-79 여,0.007667,0.057892,-0.002062,0.096371,0.004979,0.298253,0.243662,0.288687
75-79 여,0.007682,0.056795,-0.001264,0.096319,0.006022,0.299623,0.245828,0.288509
75-79 여,0.009192,0.057902,-0.000756,0.095839,0.005005,0.299988,0.241922,0.285747
75-79 여,0.007632,0.057567,-0.000310,0.095009,0.005820,0.299074,0.243131,0.287038
75-79 여,0.009191,0.055592,-0.000056,0.095930,0.003131,0.300397,0.242224,0.289436
75-79 여,0.008867,0.056145,-0.000685,0.097120,0.003703,0.300104,0.243237,0.286157
75-79 여,0.010649,0.057043,-0.000265,0.097268,0.003522,0.296632,0.241992,0.287346
75-79 여,0.008019,0.057511,-0.000382,0.098247,0.006244,0.298182,0.242643,0.287025
...,...,...,...,...,...,...,...,...
80-84 여,0.004566,0.045596,-0.000281,0.071166,0.010097,0.292022,0.265457,0.317326
80-84 여,0.002931,0.045249,-0.000202,0.069294,0.008781,0.289060,0.266237,0.318267
80-84 여,0.002944,0.045978,-0.000106,0.069549,0.010352,0.290073,0.265679,0.319081
80-84 여,0.004616,0.044396,-0.000033,0.069365,0.007962,0.290432,0.263895,0.318365
80-84 여,0.003628,0.045185,-0.000721,0.069303,0.010270,0.292775,0.265740,0.318085
80-84 여,0.003971,0.045636,-0.000934,0.069212,0.012384,0.293351,0.263966,0.316780
80-84 여,0.003916,0.043819,-0.000102,0.070184,0.007947,0.291585,0.265167,0.316919
80-84 여,0.002374,0.045016,-0.000347,0.068586,0.011955,0.291652,0.266448,0.318665
80-84 여,0.002971,0.045391,-0.000071,0.068682,0.010620,0.289566,0.264445,0.318670
80-84 여,0.003637,0.045729,-0.001265,0.070023,0.008979,0.291245,0.264131,0.318920
80-84 여,0.004565,0.044359,-0.000256,0.070769,0.009916,0.291746,0.266051,0.318209
80-84 여,0.003345,0.045667,-0.001700,0.068027,0.011517,0.289560,0.266826,0.318421
80-84 여,0.002748,0.044786,-0.000901,0.068626,0.011674,0.292780,0.266151,0.317957
80-84 여,0.004605,0.044312,-0.000588,0.069301,0.011298,0.290419,0.267260,0.318034
80-84 여,0.003397,0.046039,-0.000148,0.070344,0.010380,0.290133,0.266652,0.317728
80-84 여,0.004187,0.046710,-0.000669,0.068913,0.010457,0.290141,0.265987,0.317636
80-84 여,0.001583,0.046357,-0.000432,0.071239,0.011116,0.289160,0.265216,0.319010
80-84 여,0.006523,0.045074,-0.000241,0.070467,0.009992,0.290640,0.265151,0.317062
80-84 여,0.003089,0.046353,-0.000318,0.068737,0.012005,0.292344,0.264036,0.317167
80-84 여,0.001504,0.044642,-0.000245,0.071261,0.011129,0.292955,0.267029,0.318768
80-84 여,0.006129,0.046725,-0.001363,0.070611,0.011041,0.290302,0.264397,0.317696
80-84 여,0.003509,0.044865,-0.001885,0.070843,0.012022,0.290399,0.266300,0.319611
80-84 여,0.004827,0.044861,-0.000798,0.068763,0.009729,0.291872,0.266255,0.317085
80-84 여,0.002812,0.043791,-0.001250,0.070012,0.010349,0.293315,0.265843,0.317489
80-84 여,0.001786,0.046117,-0.000683,0.070135,0.009184,0.291378,0.267077,0.317909
80-84 여,0.002938,0.044714,-0.001012,0.070143,0.009830,0.291117,0.265667,0.318211
80-84 여,0.002730,0.044099,-0.001684,0.069166,0.009467,0.290136,0.265453,0.316842
80-84 여,0.002377,0.045818,-0.000401,0.069170,0.010013,0.291710,0.265346,0.316941
80-84 여,0.003861,0.044610,-0.000293,0.069567,0.009053,0.292240,0.264786,0.319394
80-84 여,0.003913,0.045331,-0.000408,0.068939,0.007831,0.291064,0.266184,0.320457