In [1]:
import pandas as pd
import numpy as np

In [73]:
data = pd.read_excel("여가활동통계.xlsx", header=None)

In [74]:
data.iloc[57] = data.iloc[57].replace(method='ffill')

In [75]:
data1 = data.iloc[57:67, :12].drop(1,axis=1).reset_index(drop=True)
data1

        0      2      3      4      5      6      7      8      9     10    11
0      NaN  65-69  65-69  70-74  70-74  75-79  75-79  80-84  80-84  85이상  85이상
1      NaN      남      여      남      여      남      여      남      여     남     여
2   문화예술관람   0.14   0.16   0.09   0.11   0.05   0.07   0.02   0.02  0.01  0.03
3   문화예술참여   0.71    0.8   0.64   0.76   0.57   0.69   0.23   0.35  0.07  0.18
4    스포츠관람   0.06   0.07   0.04   0.04   0.02   0.02   0.01   0.01  0.01  0.02
5    스포츠참여   1.71   1.92   1.12   1.32   0.94   1.15   0.35   0.56  0.15  0.38
6       관광    0.1   0.11   0.06   0.08   0.06   0.07   0.05   0.07  0.03  0.07
7     취미오락    4.7   5.31   3.42   4.02   2.85   3.48   1.46   2.28  0.57  1.41
8     휴식활동   3.76   4.24   3.06   3.59   2.33   2.84   1.34   2.09  0.65   1.6
9  사회 및 기타   4.36   4.91   3.23   3.79   2.74   3.34    1.6   2.49  0.65  1.59

In [76]:
data1.columns = data1.iloc[0].str.cat(data1.iloc[1], sep=' ')

In [77]:
data1

,nan,65-69 남,65-69 여,70-74 남,70-74 여,75-79 남,75-79 여,80-84 남,80-84 여,85이상 남,85이상 여
0,NaN,65-69,65-69,70-74,70-74,75-79,75-79,80-84,80-84,85이상,85이상
1,NaN,남,여,남,여,남,여,남,여,남,여
2,문화예술관람,0.14,0.16,0.09,0.11,0.05,0.07,0.02,0.02,0.01,0.03
3,문화예술참여,0.71,0.8,0.64,0.76,0.57,0.69,0.23,0.35,0.07,0.18
4,스포츠관람,0.06,0.07,0.04,0.04,0.02,0.02,0.01,0.01,0.01,0.02
5,스포츠참여,1.71,1.92,1.12,1.32,0.94,1.15,0.35,0.56,0.15,0.38
6,관광,0.1,0.11,0.06,0.08,0.06,0.07,0.05,0.07,0.03,0.07
7,취미오락,4.7,5.31,3.42,4.02,2.85,3.48,1.46,2.28,0.57,1.41
8,휴식활동,3.76,4.24,3.06,3.59,2.33,2.84,1.34,2.09,0.65,1.6
9,사회 및 기타,4.36,4.91,3.23,3.79,2.74,3.34,1.6,2.49,0.65,1.59

In [78]:
data1 = data1.drop([0,1], axis=0).reset_index(drop=True)

In [79]:
col = data1.columns.tolist()
col[0] = "분류"
data1.columns = col

In [80]:
data1.set_index("분류", inplace=True)

In [81]:
data1

,65-69 남,65-69 여,70-74 남,70-74 여,75-79 남,75-79 여,80-84 남,80-84 여,85이상 남,85이상 여
분류,,,,,,,,,,
문화예술관람,0.14,0.16,0.09,0.11,0.05,0.07,0.02,0.02,0.01,0.03
문화예술참여,0.71,0.8,0.64,0.76,0.57,0.69,0.23,0.35,0.07,0.18
스포츠관람,0.06,0.07,0.04,0.04,0.02,0.02,0.01,0.01,0.01,0.02
스포츠참여,1.71,1.92,1.12,1.32,0.94,1.15,0.35,0.56,0.15,0.38
관광,0.1,0.11,0.06,0.08,0.06,0.07,0.05,0.07,0.03,0.07
취미오락,4.7,5.31,3.42,4.02,2.85,3.48,1.46,2.28,0.57,1.41
휴식활동,3.76,4.24,3.06,3.59,2.33,2.84,1.34,2.09,0.65,1.6
사회 및 기타,4.36,4.91,3.23,3.79,2.74,3.34,1.6,2.49,0.65,1.59

In [82]:
data2=data1.T
data2

분류      문화예술관람 문화예술참여 스포츠관람 스포츠참여    관광  취미오락  휴식활동 사회 및 기타
65-69 남   0.14   0.71  0.06  1.71   0.1   4.7  3.76    4.36
65-69 여   0.16    0.8  0.07  1.92  0.11  5.31  4.24    4.91
70-74 남   0.09   0.64  0.04  1.12  0.06  3.42  3.06    3.23
70-74 여   0.11   0.76  0.04  1.32  0.08  4.02  3.59    3.79
75-79 남   0.05   0.57  0.02  0.94  0.06  2.85  2.33    2.74
75-79 여   0.07   0.69  0.02  1.15  0.07  3.48  2.84    3.34
80-84 남   0.02   0.23  0.01  0.35  0.05  1.46  1.34     1.6
80-84 여   0.02   0.35  0.01  0.56  0.07  2.28  2.09    2.49
85이상 남    0.01   0.07  0.01  0.15  0.03  0.57  0.65    0.65
85이상 여    0.03   0.18  0.02  0.38  0.07  1.41   1.6    1.59

In [83]:
data2["합"] = data2.apply(np.sum, axis=1)
data2

분류      문화예술관람 문화예술참여 스포츠관람 스포츠참여    관광  취미오락  휴식활동 사회 및 기타      합
65-69 남   0.14   0.71  0.06  1.71   0.1   4.7  3.76    4.36  15.54
65-69 여   0.16    0.8  0.07  1.92  0.11  5.31  4.24    4.91  17.52
70-74 남   0.09   0.64  0.04  1.12  0.06  3.42  3.06    3.23  11.66
70-74 여   0.11   0.76  0.04  1.32  0.08  4.02  3.59    3.79  13.71
75-79 남   0.05   0.57  0.02  0.94  0.06  2.85  2.33    2.74   9.56
75-79 여   0.07   0.69  0.02  1.15  0.07  3.48  2.84    3.34  11.66
80-84 남   0.02   0.23  0.01  0.35  0.05  1.46  1.34     1.6   5.06
80-84 여   0.02   0.35  0.01  0.56  0.07  2.28  2.09    2.49   7.87
85이상 남    0.01   0.07  0.01  0.15  0.03  0.57  0.65    0.65   2.14
85이상 여    0.03   0.18  0.02  0.38  0.07  1.41   1.6    1.59   5.28

In [84]:
data3 = data2.iloc[:,:8].div(data2.iloc[:,8], axis=0)

In [85]:
data3

분류,문화예술관람,문화예술참여,스포츠관람,스포츠참여,관광,취미오락,휴식활동,사회 및 기타
65-69 남,0.00900901,0.0456885,0.003861,0.110039,0.00643501,0.302445,0.241956,0.280566
65-69 여,0.00913242,0.0456621,0.00399543,0.109589,0.00627854,0.303082,0.242009,0.280251
70-74 남,0.0077187,0.0548885,0.00343053,0.0960549,0.0051458,0.29331,0.262436,0.277015
70-74 여,0.00802334,0.055434,0.00291758,0.0962801,0.00583516,0.293217,0.261853,0.276441
75-79 남,0.00523013,0.0596234,0.00209205,0.0983264,0.00627615,0.298117,0.243724,0.286611
75-79 여,0.00600343,0.0591767,0.00171527,0.0986278,0.00600343,0.298456,0.243568,0.286449
80-84 남,0.00395257,0.0454545,0.00197628,0.06917,0.00988142,0.288538,0.264822,0.316206
80-84 여,0.0025413,0.0444727,0.00127065,0.0711563,0.00889454,0.289708,0.265565,0.316391
85이상 남,0.0046729,0.0327103,0.0046729,0.0700935,0.0140187,0.266355,0.303738,0.303738
85이상 여,0.00568182,0.0340909,0.00378788,0.0719697,0.0132576,0.267045,0.30303,0.301136

In [86]:
people_ratio = [159,179,122,143,93,114,45,71,21,53]
data4 = pd.DataFrame()
for i, ratio in enumerate(people_ratio):
    data4 = data4.append([data3.iloc[i]]*ratio)

In [87]:
data4

분류,문화예술관람,문화예술참여,스포츠관람,스포츠참여,관광,취미오락,휴식활동,사회 및 기타
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
...,...,...,...,...,...,...,...,...
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136

In [88]:
data4.groupby(level=0).mean()

분류,문화예술관람,문화예술참여,스포츠관람,스포츠참여,관광,취미오락,휴식활동,사회 및 기타
65-69 남,0.009009,0.045689,0.003861,0.110039,0.006435,0.302445,0.241956,0.280566
65-69 여,0.009132,0.045662,0.003995,0.109589,0.006279,0.303082,0.242009,0.280251
70-74 남,0.007719,0.054889,0.003431,0.096055,0.005146,0.293310,0.262436,0.277015
70-74 여,0.008023,0.055434,0.002918,0.096280,0.005835,0.293217,0.261853,0.276441
75-79 남,0.005230,0.059623,0.002092,0.098326,0.006276,0.298117,0.243724,0.286611
75-79 여,0.006003,0.059177,0.001715,0.098628,0.006003,0.298456,0.243568,0.286449
80-84 남,0.003953,0.045455,0.001976,0.069170,0.009881,0.288538,0.264822,0.316206
80-84 여,0.002541,0.044473,0.001271,0.071156,0.008895,0.289708,0.265565,0.316391
85이상 남,0.004673,0.032710,0.004673,0.070093,0.014019,0.266355,0.303738,0.303738
85이상 여,0.005682,0.034091,0.003788,0.071970,0.013258,0.267045,0.303030,0.301136

In [89]:
np.set_printoptions(suppress = False)
data5 = pd.DataFrame()
for index in data4.index.unique():
    temp = data4.loc[index,:]
    for column in data4.columns:
        normal_random = np.random.normal(temp.loc[index,column].iloc[0], 1, len(temp))
        temp.loc[:,column] = normal_random
    data5 = data5.append(temp)

In [90]:
data5.groupby(level=0).mean()

분류,문화예술관람,문화예술참여,스포츠관람,스포츠참여,관광,취미오락,휴식활동,사회 및 기타
65-69 남,-0.042749,0.019239,0.033059,0.102083,-0.037525,0.328739,0.334706,0.398182
65-69 여,0.095847,0.098876,0.039279,0.097206,0.029447,0.328057,0.243482,0.242028
70-74 남,-0.046777,0.218338,-0.018122,0.229825,0.021424,0.361944,0.380713,0.273258
70-74 여,0.028425,0.143953,-0.085456,0.009874,0.030080,0.382548,0.231650,0.448543
75-79 남,-0.042952,0.077411,0.024466,0.085197,-0.130427,0.349359,0.108950,0.318937
75-79 여,-0.021557,0.071953,-0.150939,0.193893,0.071699,0.136032,0.325671,0.302029
80-84 남,0.243413,0.078823,-0.161655,-0.052492,-0.011158,0.326325,0.169918,0.515603
80-84 여,-0.061171,0.076544,0.059893,0.136520,-0.049161,0.261350,0.205592,0.356423
85이상 남,-0.140978,0.236224,0.237765,0.133450,0.170901,0.154764,-0.067785,0.526110
85이상 여,-0.298824,0.011163,-0.356845,0.195795,0.051774,0.269675,0.095530,0.370509

In [91]:
data5[~(data5>0).all(1)]

분류,문화예술관람,문화예술참여,스포츠관람,스포츠참여,관광,취미오락,휴식활동,사회 및 기타
65-69 남,-0.933495,-0.162088,-0.057024,0.041401,-0.712065,0.041560,0.946653,0.421195
65-69 남,-1.439223,-1.407764,0.290672,0.113497,0.638476,-0.081597,2.906510,-0.387580
65-69 남,-1.713132,-0.096850,-0.203200,-0.949143,1.158938,-1.617325,0.038188,0.127611
65-69 남,0.618129,-1.113826,0.401349,0.351410,-0.237245,0.083291,-0.243314,-1.037382
65-69 남,0.131447,1.363377,1.346937,1.405123,1.316866,0.666368,0.790752,-0.606344
65-69 남,0.784277,0.766259,1.052514,0.617777,0.060996,-0.667893,-0.165881,-1.123760
65-69 남,-0.676729,-1.452019,-0.539125,-1.642989,0.016665,0.182055,0.824116,-0.982387
65-69 남,-0.186854,0.325494,2.061638,1.063207,0.590000,0.341545,0.494069,-0.321047
65-69 남,0.204197,0.181483,1.715576,-0.611716,-1.484232,1.227299,1.050686,1.295466
65-69 남,-0.447283,0.721018,1.668182,1.717522,-0.256306,0.597259,0.256123,0.681109
65-69 남,-2.258992,0.760416,1.729854,0.848368,-0.861059,2.192384,-0.972348,0.525002
65-69 남,-2.292041,-1.030773,0.334196,1.615913,-1.099831,1.821607,-1.289351,-1.065332
65-69 남,0.065373,0.740184,-1.386749,-1.124014,-0.228275,0.495574,-1.570428,0.175709
65-69 남,0.843266,0.228826,-0.510709,-0.216764,1.171540,1.707267,2.625009,0.297240
65-69 남,-1.165642,-0.327447,-0.160957,0.155823,-0.115447,-2.245439,1.380856,-0.441308
65-69 남,1.181596,0.706693,-0.922527,-0.263127,-0.883093,2.179182,1.385234,0.437587
65-69 남,0.638441,0.724699,-0.238380,0.460223,1.321651,0.377178,0.032500,1.575991
65-69 남,0.020995,0.405270,-0.543595,-0.115001,-0.836069,-1.500980,0.328385,-0.932117
65-69 남,2.183169,0.357778,-2.310920,-0.150955,-0.596908,1.388346,0.734039,-0.003871
65-69 남,0.225374,-1.418815,-0.535845,0.759423,-0.709352,0.562079,1.360469,1.190939
65-69 남,-0.563540,-0.877420,0.605470,1.791316,-0.047920,0.454368,-1.933056,2.358913
65-69 남,-0.444346,1.345582,0.836817,0.004764,-1.452376,0.959599,0.548260,0.127187
65-69 남,-1.264585,0.060927,0.079973,-0.356385,-0.076060,0.006109,1.485069,0.925722
65-69 남,0.642263,0.383525,-1.214654,-0.290174,-0.608403,1.322091,0.987690,1.484857
65-69 남,0.202250,0.322992,-0.902771,-0.892828,1.344480,1.169280,0.249407,2.925316
65-69 남,-1.394158,-0.108056,0.458000,-0.599460,1.469858,0.963883,-1.222688,-1.073613
65-69 남,-1.332768,-0.107586,-0.181076,0.669594,-1.443920,0.084631,0.486048,-0.871685
65-69 남,0.577526,0.305743,-0.134165,-1.033977,0.401438,-0.513036,1.874280,0.152539
65-69 남,-0.805235,1.923496,-0.980429,1.102528,-0.253372,1.601724,0.089619,-0.599930
65-69 남,1.283793,-1.841930,2.197090,-2.459962,1.711056,-0.192943,0.259841,1.931932
...,...,...,...,...,...,...,...,...
85이상 여,-0.030579,-0.617938,-2.253670,-0.134601,1.203244,0.064725,1.543755,-0.583789
85이상 여,-0.935389,0.346070,-0.781176,-0.695219,-0.328144,1.038655,0.266075,-1.931725
85이상 여,-0.350412,-0.959160,1.579222,-0.359788,-0.078405,-0.333123,1.320475,1.305299
85이상 여,1.154740,-0.754326,-2.309298,1.919190,-0.554547,-0.113861,-0.072587,0.266551
85이상 여,-0.858664,0.140171,-0.612828,-0.377635,0.749436,1.171464,1.942995,1.282392
85이상 여,-0.241178,1.266518,1.518012,0.043187,-2.257584,-0.716726,-1.459204,0.663976
85이상 여,0.347274,0.125480,0.845334,0.749075,-0.751251,0.161773,-0.495066,1.235315
85이상 여,1.265789,-0.029006,-0.237525,0.684425,1.460596,-0.422728,-0.313167,0.795193
85이상 여,-1.411399,-0.452205,-0.957324,-1.206310,-0.550746,-0.222808,0.817176,0.505828
85이상 여,0.029023,1.150339,1.127100,-3.667330,-0.187299,-1.510197,-1.318025,-1.060195
85이상 여,0.208643,0.678386,-0.483675,0.790911,-1.088049,1.612714,-0.373889,-0.960212
85이상 여,0.481147,-0.084770,-0.604665,1.062482,0.375982,-0.419260,-0.294056,-0.417565
85이상 여,-0.705602,0.698133,-1.602410,-0.535393,-0.138262,0.315868,3.110367,0.413580
85이상 여,-0.462612,0.242971,-1.143861,0.188646,-1.386223,0.008040,-1.286093,3.034552
85이상 여,-0.716103,0.221030,-0.586766,0.054680,-1.312198,0.458710,-1.184504,0.648869
85이상 여,-0.190102,-0.049737,-1.873690,0.416341,0.623483,0.547517,0.266827,-0.445634
85이상 여,-0.328397,0.238579,0.294031,0.944931,0.392703,-0.112251,0.045456,1.794777
85이상 여,-0.743828,-0.111996,-0.265830,-0.974027,1.489588,0.474286,1.392262,2.384999
85이상 여,0.377277,-0.721674,1.143173,1.298335,1.510948,-0.672967,1.450976,1.046110
85이상 여,0.008052,0.566844,-1.524934,0.459754,1.277746,0.490487,0.244424,0.409099
85이상 여,0.394285,0.046017,-0.607066,0.159227,0.796952,-0.594924,0.871887,1.231390
85이상 여,-0.654108,-1.590254,-2.356251,-0.662980,0.599738,-0.400906,-0.395080,-0.224876
85이상 여,0.440244,1.470010,-1.464161,0.379930,-2.045744,-0.564525,-0.333249,0.637551
85이상 여,-0.972527,0.500845,0.389346,-0.674436,0.137138,-0.040294,-0.486639,0.722795
85이상 여,-0.873165,-0.495697,0.560804,0.216881,-2.097369,1.261691,1.843094,-0.809182
85이상 여,-0.577677,-0.302138,-1.233290,0.527404,1.119171,0.256887,-0.639915,1.892269
85이상 여,1.789638,-0.948633,0.405947,1.974043,-0.622682,1.682712,0.891705,0.088120
85이상 여,-0.279106,-1.691847,-1.951899,0.103911,-0.270336,1.679686,-0.090816,-0.163005
85이상 여,1.590326,-0.013614,0.664557,-1.361589,0.382149,-1.427027,-1.235006,-1.678925
85이상 여,-0.953307,0.209372,0.370800,1.217449,-0.399510,0.474537,-0.531570,-0.716891

In [92]:
len(data5)

1000

In [93]:
data5.to_excel("최종가짜데이터.xlsx")